server:
  tomcat:
    accesslog:
      directory: ./logs/tomcat/
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\trequest: %r\tstatus_code: %s\tremote_ip: %a\tlocal_ip: %A\t details: %{User-Agent}i"
      suffix: .log

logging:
  file:
    name: ./logs/application/application.log
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: ./logs/application/logs/application_log-%d{yyyy-MM-dd}.%i.log
      max-file-size: 30MB

spring:
  profiles:
    active: local
  application:
    name: example
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
---
server:
  tomcat:
    accesslog:
      directory: /var/log/tomcat/
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\trequest: %r\tstatus_code: %s\tremote_ip: %a\tlocal_ip: %A\t details: %{User-Agent}i"
      suffix: .log

logging:
  file:
    name: /var/log/spring/application.log
  level:
    root: info
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/app/application/logs/application-%d{yyyy-MM-dd}.%i.log
      max-file-size: 30MB

spring:
  profiles:
    active: prod
  application:
    name: example
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}
